import React from "react";
import { isAutoGeneratedLineDescription } from "../jobs/productionPlainLanguage.js";

function lineTotal(item) {
  return item.chargeComponents?.reduce((acc, c) => acc + (c.amount || 0), 0) || item.totalAmount || 0;
}

export default function QuotationLineItemsTable({
  quotation,
  detailLineIndex = null,
  onSelectLine,
  fillHeight = false,
  hidePricing = false,
  title = "Quotation items",
}) {
  const lines = quotation?.lineItems || [];
  const currency = quotation?.currency || "INR";

  if (!lines.length) {
    return (
      <section className="border-gov-border bg-white flex flex-col min-w-0 flex-1 min-h-0">
        <div className="px-3 py-1.5 border-b border-gov-border bg-gray-50">
          <span className="text-[11px] font-semibold text-gray-600 uppercase tracking-wide">{title}</span>
        </div>
        <div className="flex flex-1 items-center justify-center p-8 text-[11px] text-gray-400 uppercase tracking-wide">
          No items on this quotation
        </div>
      </section>
    );
  }

  return (
    <section
      className={`border-gov-border bg-white flex flex-col min-w-0 ${
        fillHeight ? "flex-1 min-h-0 border-b-0" : "shrink-0 border-b"
      }`}
    >
      <div className="px-3 py-1.5 border-b border-gov-border bg-gray-50 flex items-center justify-between gap-2">
        <span className="text-[11px] font-semibold text-gray-600 uppercase tracking-wide">{title}</span>
        <span className="text-[10px] text-gray-500 hidden sm:inline">
          Quote <strong className="text-gov-blue">{quotation.quoteNumber || "—"}</strong>
        </span>
      </div>

      <div className={`overflow-x-auto ${fillHeight ? "flex-1 min-h-0 overflow-y-auto" : ""}`}>
        <table className="gov-table w-full">
          <thead className="sticky top-0 z-[1] bg-gray-50 shadow-[0_1px_0_0_#d1d5db]">
            <tr>
              <th className="w-12 pl-3">#</th>
              <th className="min-w-[180px]">Item</th>
              <th className="w-16 text-center">Qty</th>
              <th className="w-24">Type</th>
              {!hidePricing && <th className="w-28 text-right pr-3">Total</th>}
            </tr>
          </thead>
          <tbody>
            {lines.map((line, index) => {
              const itemTitle = line.meta?.itemTitle || line.title || `Line ${index + 1}`;
              const showDescription = line.description && !isAutoGeneratedLineDescription(line.description);
              const isDetail = detailLineIndex === index;
              const clickable = Boolean(onSelectLine);
              const total = lineTotal(line);

              return (
                <tr
                  key={line.id || line._id || index}
                  className={`${clickable ? "cursor-pointer hover:bg-gray-50" : ""} ${
                    isDetail ? "bg-gov-blue-light/30" : ""
                  }`}
                  onClick={clickable ? () => onSelectLine?.(index) : undefined}
                >
                  <td className="pl-3 align-top text-gray-500 tabular-nums">{index + 1}</td>
                  <td className="align-top min-w-0 max-w-[320px]">
                    <div className={`font-semibold truncate ${clickable ? "text-gov-blue" : "text-gray-700"}`}>
                      {itemTitle}
                    </div>
                    {showDescription && (
                      <div className="text-xs text-gray-500 line-clamp-2 leading-snug mt-0.5">{line.description}</div>
                    )}
                  </td>
                  <td className="align-top text-center tabular-nums">{line.quantity ?? 1}</td>
                  <td className="align-top text-xs text-gray-600">{line.lineKind || "PRINTING"}</td>
                  {!hidePricing && (
                    <td className="align-top text-right pr-3 tabular-nums">
                      <div className="text-xs font-bold text-gov-blue">{total.toLocaleString()}</div>
                      <div className="text-[9px] text-gray-400">{currency}</div>
                    </td>
                  )}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </section>
  );
}
