import { bindingLabel, detectWorkType } from "./JobItemProductionDetails.jsx";
import { layoutPreviewPropsFromItem } from "../../components/quotes/layoutPreviewProps.js";

export function workTypeLabel(workType) {
  if (workType === "brochure") return "Booklet printing";
  return "Normal printing";
}

function sidesLabel(sides) {
  if (sides === "DOUBLE") return "Front and back";
  if (sides === "SINGLE") return "Front only";
  return sides || null;
}

function colorLabel(mode) {
  if (mode === "BW") return "Black & white";
  if (mode === "COLOR") return "Full colour";
  return mode || null;
}

function formatBrochureColor(input) {
  const trimmed = input?.trim();
  if (!trimmed) return "Black & white only";
  if (/^b&w$/i.test(trimmed) || /^bw$/i.test(trimmed) || /black\s*&?\s*white/i.test(trimmed)) {
    return "Black & white only";
  }
  return trimmed;
}

function brochureSignatureSummary(plan) {
  if (!plan?.signatures?.length) return null;
  return plan.signatures.map((sig) => `${sig.signaturePages}pp`).join(" + ");
}

/** Matches brochure orientation labels in the quotation editor. */
export function resolveBrochureApiOrientation(meta) {
  if (!meta || typeof meta !== "object") return "NORMAL";
  const fromPlan = meta.nestedPrintPlan?.signatures?.[0]?.imposition?.orientation;
  if (fromPlan === "NORMAL" || fromPlan === "ROTATED") return fromPlan;
  if (meta.brochureOrientation === "NORMAL" || meta.brochureOrientation === "ROTATED") {
    return meta.brochureOrientation;
  }
  if (meta.pageNumberingOrientation === "NORMAL" || meta.pageNumberingOrientation === "ROTATED") {
    return meta.pageNumberingOrientation;
  }
  return "NORMAL";
}

export function brochureReaderLayoutLabel(orientation) {
  return orientation === "ROTATED" ? "Rotated" : "Normal";
}

/** Single consolidated booklet spec list — avoids repeating binding, copies, sheets, etc. */
export function buildBrochureDisplaySpecs(item, options = {}) {
  const meta = item?.meta && typeof item.meta === "object" ? item.meta : {};
  const plan = meta.nestedPrintPlan;
  const copies = meta.brochureCopies ?? item.quantity ?? 1;
  const pages = meta.brochurePagesPerBrochure;
  const sigSummary = brochureSignatureSummary(plan);
  const runs = plan?.printRunCount;

  const specs = [
    { label: "Job type", value: workTypeLabel("brochure") },
    { label: "Binding", value: bindingLabel(meta.bookletBindingType) },
    { label: "Booklet", value: pages ? `${pages} pages · ${copies} copies` : `${copies} copies` },
    {
      label: "Orientation",
      value: brochureReaderLayoutLabel(resolveBrochureApiOrientation(meta)),
      brochureOrientation: resolveBrochureApiOrientation(meta),
    },
    { label: "Colour", value: formatBrochureColor(meta.brochureColorPagesInput) },
  ];

  if (sigSummary) {
    specs.push({
      label: "Signatures",
      value: runs ? `${sigSummary} (${runs} print run${runs === 1 ? "" : "s"})` : sigSummary,
    });
  }

  if (plan?.printedSheetsForCopies != null) {
    specs.push({ label: "Sheets to print", value: plan.printedSheetsForCopies });
  }
  if (plan?.totals?.prints != null) {
    specs.push({ label: "Impressions", value: plan.totals.prints });
  }
  if (!options.hidePricing && plan?.totals?.price != null) {
    specs.push({ label: "Quoted total", value: `₹ ${Number(plan.totals.price).toLocaleString()}` });
  }

  return specs.filter((s) => s.value != null && s.value !== "");
}

/** Quote line descriptions like "BKT • Center Clip • 8pp • …" repeat structured meta — hide in preview. */
export function isAutoGeneratedLineDescription(description) {
  if (!description || typeof description !== "string") return false;
  return /^(BKT|LSR|OFS|OFF|JOB)\s*•/i.test(description.trim());
}

function paperHintFromDescription(description) {
  if (!description || typeof description !== "string") return null;
  if (isAutoGeneratedLineDescription(description)) return null;
  const parts = description.split("•").map((p) => p.trim()).filter(Boolean);
  if (parts.length >= 2) {
    return parts[parts.length - 1];
  }
  return null;
}

function stockSizeLabel(meta) {
  if (meta.customWidth && meta.customBreadth) {
    return `${meta.customWidth} × ${meta.customBreadth} ${meta.customUnit || "mm"}`;
  }
  return null;
}

/** Plain-language production summary for shop-floor staff (non-quotation users). */
export function buildPlainProductionSpecs(item, options = {}) {
  const meta = item?.meta && typeof item.meta === "object" ? item.meta : {};
  const workType = options.workType ?? detectWorkType(meta);

  if (workType === "brochure") {
    return buildBrochureDisplaySpecs(item, options);
  }

  const layoutPreview =
    options.layoutPreview ?? layoutPreviewPropsFromItem(item, meta, { hidePricing: options.hidePricing });
  const paperHint = paperHintFromDescription(item.description);

  const specs = [
    { label: "Job type", value: workTypeLabel(workType) },
    { label: "Task name", value: meta.itemTitle || item.title },
    { label: "Copies needed", value: item.quantity ?? 1 },
  ];

  if (paperHint) {
    specs.push({ label: "Paper / stock", value: paperHint });
  }

  const sizeLabel = stockSizeLabel(meta);
  if (sizeLabel) {
    specs.push({ label: "Finished size", value: sizeLabel });
  }

  if (workType === "laser" || workType === "offset") {
    specs.push(
      { label: "Printer machine", value: meta.printerModelName || "Not specified" },
      { label: "Print sides", value: sidesLabel(meta.laserSides || meta.offsetSides) },
      { label: "Colour mode", value: colorLabel(meta.laserColorMode || meta.offsetColorMode) },
    );

    if (layoutPreview.piecesPerSheet) {
      specs.push({ label: "Layout (up)", value: `${layoutPreview.piecesPerSheet} pieces per sheet` });
    }
    if (layoutPreview.sheets != null) {
      specs.push({ label: "Sheets to print", value: layoutPreview.sheets });
    }
    if (
      layoutPreview.parentSheets != null &&
      layoutPreview.parentSheets !== layoutPreview.sheets
    ) {
      specs.push({ label: "Full paper sheets", value: layoutPreview.parentSheets });
    }
    if (layoutPreview.prints != null) {
      specs.push({ label: "Total impressions", value: layoutPreview.prints });
    }

    if (workType === "offset" && meta.offsetWaste != null) {
      specs.push({ label: "Colour adjustment sheets", value: meta.offsetWaste });
    }
  }

  return specs.filter((s) => s.value != null && s.value !== "");
}

export function findJobForQuotationLine(jobs, lineIndex) {
  for (const job of jobs || []) {
    const item = (job.items || []).find((i) => i.quotationLineIndex === lineIndex);
    if (item) return { job, item };
  }
  return null;
}

export function itemPrimaryTaskStatus(item) {
  const tasks = item?.tasks || [];
  if (!tasks.length) return "PENDING";
  return tasks[0].status;
}

export function itemPrimaryTaskAssignee(item) {
  const task = item?.tasks?.[0];
  return task?.assignedTo?.displayName || task?.assignedTo?.name || task?.assignedTo?.email || null;
}
