import React, { useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { findJobForQuotationLine, isAutoGeneratedLineDescription, itemPrimaryTaskStatus } from "./productionPlainLanguage.js";

const JOB_STATUS_CONFIG = {
  OPEN: { label: "Open", class: "bg-gray-100 text-gray-700" },
  IN_PROGRESS: { label: "In progress", class: "bg-gov-blue-light text-gov-blue border border-gov-blue/20" },
  ON_HOLD: { label: "On hold", class: "bg-amber-100 text-amber-800" },
  COMPLETED: { label: "Completed", class: "bg-green-100 text-green-800" },
  CANCELLED: { label: "Cancelled", class: "bg-gray-200 text-gray-500" },
};

const TASK_STATUS_CONFIG = {
  PENDING: { label: "Pending", class: "bg-gray-100 text-gray-600" },
  IN_PROGRESS: { label: "In progress", class: "bg-gov-blue-light text-gov-blue border border-gov-blue/20" },
  COMPLETED: { label: "Completed", class: "bg-green-100 text-green-800" },
  CANCELLED: { label: "Cancelled", class: "bg-gray-200 text-gray-500" },
};

function displayUser(user) {
  if (!user) return "—";
  return user.displayName || user.name || user.email || "—";
}

function StatusBadge({ status, configMap }) {
  const config = configMap[status];
  if (!config) return <span className="text-gray-400">—</span>;
  return (
    <span className={`inline-block text-[9px] font-semibold px-1.5 py-px whitespace-nowrap ${config.class}`}>
      {config.label}
    </span>
  );
}

export default function QuoteProductionStatus({
  quotation,
  quoteJobs = [],
  currentJobId,
  title = "Items",
  pickMode = false,
  groupByCurrentJob = false,
  selectedIndices = [],
  detailLineIndex = null,
  onToggleLine,
  onSelectLine,
  headerAction = null,
  fillHeight = false,
}) {
  const navigate = useNavigate();
  const lines = quotation?.lineItems || [];
  if (!lines.length) return null;

  const showActions = lines.some((_, index) => {
    const job = findJobForQuotationLine(quoteJobs, index)?.job;
    return job && job.id !== currentJobId;
  });

  const totalCols = 6 + (showActions ? 1 : 0);

  const { primaryIndices, secondaryIndices } = useMemo(() => {
    const all = lines.map((_, index) => index);
    if (!groupByCurrentJob || !currentJobId) {
      return { primaryIndices: all, secondaryIndices: [] };
    }
    const primary = all.filter((index) => findJobForQuotationLine(quoteJobs, index)?.job?.id === currentJobId);
    const secondary = all.filter((index) => !primary.includes(index));
    return { primaryIndices: primary, secondaryIndices: secondary };
  }, [lines, groupByCurrentJob, currentJobId, quoteJobs]);

  function renderRow(index, displayNumber, interactive) {
    const line = lines[index];
    const match = findJobForQuotationLine(quoteJobs, index);
    const job = match?.job;
    const item = match?.item;
    const isCurrent = job?.id === currentJobId;
    const taskStatus = item ? itemPrimaryTaskStatus(item) : null;
    const canPick = pickMode && !job;
    const picked = selectedIndices.includes(index);
    const isDetail = detailLineIndex === index;
    const itemTitle = line.meta?.itemTitle || line.title || `Line ${index + 1}`;
    const showDescription = line.description && !isAutoGeneratedLineDescription(line.description);
    const clickable = interactive && Boolean(onSelectLine);

    return (
      <tr
        key={line.id || line._id || index}
        className={`${clickable ? "cursor-pointer hover:bg-gray-50" : "text-gray-600"} ${
          isCurrent || isDetail ? "bg-gov-blue-light/30" : picked ? "bg-gov-blue-light/15" : ""
        } ${!interactive ? "opacity-80" : ""}`}
        onClick={clickable ? () => onSelectLine?.(index) : undefined}
      >
        <td onClick={(e) => pickMode && canPick && e.stopPropagation()}>
          <div className="flex items-center gap-1.5">
            {pickMode &&
              (canPick ? (
                <input
                  type="checkbox"
                  checked={picked}
                  onChange={() => onToggleLine?.(index)}
                  aria-label={`Select line ${index + 1} for job creation`}
                  className="shrink-0"
                />
              ) : (
                <span className="w-4 shrink-0" aria-hidden />
              ))}
            <span className="text-gray-500 tabular-nums">{displayNumber}</span>
          </div>
        </td>
        <td className="min-w-0 max-w-[240px]">
          <div className={`text-xs font-semibold truncate ${interactive ? "text-gov-blue" : "text-gray-700"}`}>{itemTitle}</div>
          {showDescription && (
            <div className="text-[10px] text-gray-500 line-clamp-1 leading-snug mt-px">{line.description}</div>
          )}
        </td>
        <td>
          {job ? (
            isCurrent ? (
              <span className="text-[11px] font-semibold text-gov-blue tabular-nums">{job.jobNumber || "This job"}</span>
            ) : (
              <span className="text-[11px] font-medium text-gov-blue tabular-nums">{job.jobNumber || "—"}</span>
            )
          ) : (
            <span className="text-[11px] text-gray-400">Not created</span>
          )}
        </td>
        <td>
          {job ? <StatusBadge status={job.status} configMap={JOB_STATUS_CONFIG} /> : <span className="text-gray-400">—</span>}
        </td>
        <td className="text-xs truncate max-w-[100px]">{job ? displayUser(job.assignedTo) : "—"}</td>
        <td>
          {taskStatus ? (
            <StatusBadge status={taskStatus} configMap={TASK_STATUS_CONFIG} />
          ) : (
            <span className="text-gray-400">—</span>
          )}
        </td>
        {showActions && (
          <td className="pr-3 align-top text-right">
            {job && !isCurrent ? (
              <button
                type="button"
                className="inline-flex items-center px-1.5 py-0.5 text-[9px] font-semibold text-gov-blue border border-gov-border bg-white hover:bg-gray-50 whitespace-nowrap"
                onClick={(e) => {
                  e.stopPropagation();
                  navigate(`/dashboard/jobs/${job.id}`);
                }}
              >
                Go to job
              </button>
            ) : null}
          </td>
        )}
      </tr>
    );
  }

  return (
    <section
      className={`border-gov-border bg-white flex flex-col min-w-0 ${
        fillHeight ? "flex-1 min-h-0 border-b-0" : "shrink-0 border-b"
      }`}
    >
      <div className="px-2 py-1 border-b border-gov-border bg-gray-50 flex items-center justify-between gap-2">
        <span className="text-[11px] font-semibold text-gray-600 uppercase tracking-wide">{title}</span>
        <div className="flex items-center gap-3 shrink-0">
          <span className="text-[10px] text-gray-500 hidden sm:inline">
            Quote <strong className="text-gov-blue">{quotation.quoteNumber || "—"}</strong>
          </span>
          {headerAction}
        </div>
      </div>

      <div className={`overflow-x-auto ${fillHeight ? "flex-1 min-h-0 overflow-y-auto" : ""}`}>
        <table className="gov-table w-full">
          <thead className="sticky top-0 z-[1] bg-gray-50 shadow-[0_1px_0_0_#d1d5db]">
            <tr>
              <th className="w-10">#</th>
              <th className="min-w-[140px]">Item</th>
              <th className="w-20">Job</th>
              <th className="w-24">Job status</th>
              <th className="w-24">Assignee</th>
              <th className="w-24">Task status</th>
              {showActions && <th className="w-20 text-right">Action</th>}
            </tr>
          </thead>
          <tbody>
            {groupByCurrentJob && primaryIndices.length > 0 && (
              <tr className="bg-gov-blue-light/20">
                <td colSpan={totalCols} className="px-3 py-1 text-[10px] font-semibold uppercase tracking-wide text-gov-blue">
                  This job ({primaryIndices.length})
                </td>
              </tr>
            )}
            {groupByCurrentJob
              ? primaryIndices.map((index, idx) => renderRow(index, idx + 1, true))
              : primaryIndices.map((index) => renderRow(index, index + 1, Boolean(onSelectLine)))}

            {groupByCurrentJob && secondaryIndices.length > 0 && (
              <>
                <tr className="bg-gray-100">
                  <td
                    colSpan={totalCols}
                    className="px-3 py-1.5 text-[10px] font-semibold uppercase tracking-wide text-gray-500 border-y border-gov-border"
                  >
                    Other items on this quotation ({secondaryIndices.length})
                  </td>
                </tr>
                {secondaryIndices.map((index) => renderRow(index, index + 1, Boolean(onSelectLine)))}
              </>
            )}
          </tbody>
        </table>
      </div>
    </section>
  );
}
